#cloud-config
package_upgrade: true
packages:
  - curl
  - git
  - nginx
  - ufw
  - docker.io
  - docker-compose

write_files:
  - path: /etc/nginx/sites-available/nextjs
    content: |
      server {
        listen 80;
        server_name _;
        
        location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }

runcmd:
  # Настройка временной зоны
  - timedatectl set-timezone Europe/Moscow

  # Установка Node.js 20.x
  - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs

  # Установка pnpm
  - curl -fsSL https://get.pnpm.io/install.sh | sh -
  - source /root/.bashrc

  # Настройка firewall
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw --force enable

  # Настройка Nginx
  - ln -s /etc/nginx/sites-available/nextjs /etc/nginx/sites-enabled/
  - rm /etc/nginx/sites-enabled/default
  - systemctl restart nginx

  # Создание пользователя для приложения
  - useradd -m -s /bin/bash app
  - mkdir -p /home/app/imagify
  - chown -R app:app /home/app/imagify

  # Настройка Docker
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker app

  # Клонирование репозитория и установка зависимостей
  - su - app -c 'git clone https://github.com/ExpansesLab/imagify.git /home/app/imagify'
  - cd /home/app/imagify
  - su - app -c 'cd /home/app/imagify && pnpm install'
  - chown -R app:app /home/app/imagify

  # Настройка swap для лучшей производительности
  - fallocate -l 4G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab

  # Оптимизация системы
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
  - echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
  - sysctl -p

power_state:
  mode: reboot
  timeout: 30
  condition: True
